import {
  ContentWrapper,
  Nav,
  RightNav,
} from "@/app/(dashboards)/dashboard/sections";
import { SITE_NAV_LIST_ITEMS } from "@/constants/site-dashboard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const siteId = 1; // TODO: get siteId from context
  const linksWithSiteId = SITE_NAV_LIST_ITEMS.map((item) => {
    if (!item.link) return item;
    return {
      ...item,
      link: item.link.replace(":siteId", `/${siteId.toString()}`),
    };
  });
  return (
    <>
      <Nav />
      <RightNav navListItems={linksWithSiteId} />
      <ContentWrapper>{children}</ContentWrapper>
    </>
  );
}
